alter table CM_ENROLLMENTRECORD_T drop constraint FK371AA8DF6B67A391;
alter table CM_COURSEOFFERING_T drop constraint FKD254CBEB8B4970AE;
alter table CM_COURSEOFFERING_T drop constraint FKD254CBEBCA525211;
alter table CM_COURSEOFFERING_T drop constraint FKD254CBEBA459A5D9;
alter table CM_COURSEOFFERING_T drop constraint FKD254CBEB21961636;
alter table CM_PARTICIPATIONRECORD_T drop constraint FKA9134DF2F65C8CAE;
alter table CM_CANONICALCOURSE_T drop constraint FKDD9E516F49D9D37C;
alter table CM_COURSESECTION_T drop constraint FKE6425DCA6B67A391;
alter table CM_COURSESECTION_T drop constraint FKE6425DCACA525211;
alter table CM_COURSESECTION_T drop constraint FKE6425DCA1880BC9F;
alter table CM_COURSESECTION_T drop constraint FKE6425DCA722420D7;
alter table CM_COURSESECTION_T drop constraint FKE6425DCAEA261936;
drop table CM_ENROLLMENTSTATUS_T if exists;
drop table CM_ENROLLMENTRECORD_T if exists;
drop table CM_COURSEOFFERINGTYPE_T if exists;
drop table CM_COURSEOFFERING_T if exists;
drop table CM_COURSESETTYPE_T if exists;
drop table CM_CANONICALCOURSESTATUS_T if exists;
drop table CM_PARTICIPATIONRECORD_T if exists;
drop table CM_COURSEOFFERINGSTATUS_T if exists;
drop table CM_COURSESECTIONTYPE_T if exists;
drop table CM_COURSESECTIONSTATUS_T if exists;
drop table CM_CANONICALCOURSE_T if exists;
drop table CM_SESSION_T if exists;
drop table CM_ENROLLMENTTYPE_T if exists;
drop table CM_CANONICALCOURSESET_T if exists;
drop table CM_PARTICIPATIONSTATUS_T if exists;
drop table CM_COURSESECTION_T if exists;
drop table CM_COURSESET_T if exists;
drop table CM_SESSIONTYPE_T if exists;
create table CM_ENROLLMENTSTATUS_T (
   ENROLLMENTSTATUSID bigint generated by default as identity (start with 1),
   AUTHORITY varchar(255) not null,
   DOMAIN varchar(255) not null,
   KEYWORD varchar(255) not null,
   DISPLAYNAME varchar(255),
   DESCRIPTION varchar(255),
   UUID varchar(255) not null,
   STATUS integer not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null
);
create table CM_ENROLLMENTRECORD_T (
   ENROLLMENTRECORDID bigint generated by default as identity (start with 1),
   AGENT varchar(255) not null,
   ROLE varchar(255),
   CREDITS varchar(255),
   COURSEOFFERINGUUID varchar(255),
   COURSESECTIONUUID varchar(255) not null,
   UUID varchar(255) not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   ENROLLMENTSTATUSID bigint,
   COURSESECTIONID bigint
);
create table CM_COURSEOFFERINGTYPE_T (
   COURSEOFFERINGTYPEID bigint generated by default as identity (start with 1),
   AUTHORITY varchar(255) not null,
   DOMAIN varchar(255) not null,
   KEYWORD varchar(255) not null,
   DISPLAYNAME varchar(255),
   DESCRIPTION varchar(255),
   UUID varchar(255) not null,
   STATUS integer not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null
);
create table CM_COURSEOFFERING_T (
   COURSEOFFERINGID bigint generated by default as identity (start with 1),
   TITLE varchar(255) not null,
   DESCRIPTION varchar(255),
   OFFERINGNUMBER varchar(255) not null,
   SESSIONID bigint,
   MAXIMUMSTUDENTS integer,
   DEFAULTLOCATION varchar(255),
   DEFAULTMEETINGTIME varchar(255),
   DEFAULTSCHEDULE varchar(255),
   ISCROSSLISTED bit,
   EQUIVALENTS varchar(255),
   COURSEOFFERINGSTATUSID bigint,
   COURSEOFFERINGTYPEID bigint,
   CANONICALCOURSEUUID varchar(255) not null,
   ENROLLMENTTYPEID bigint,
   UUID varchar(255) not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   CANONICALCOURSEID bigint
);
create table CM_COURSESETTYPE_T (
   COURSESETTYPEID bigint generated by default as identity (start with 1),
   AUTHORITY varchar(255) not null,
   DOMAIN varchar(255) not null,
   KEYWORD varchar(255) not null,
   DISPLAYNAME varchar(255),
   DESCRIPTION varchar(255),
   UUID varchar(255) not null,
   STATUS integer not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null
);
create table CM_CANONICALCOURSESTATUS_T (
   CANONICALCOURSESTATUSID bigint generated by default as identity (start with 1),
   AUTHORITY varchar(255) not null,
   DOMAIN varchar(255) not null,
   KEYWORD varchar(255) not null,
   DISPLAYNAME varchar(255),
   DESCRIPTION varchar(255),
   UUID varchar(255) not null,
   STATUS integer not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null
);
create table CM_PARTICIPATIONRECORD_T (
   PARTICIPATIONRECORDID bigint generated by default as identity (start with 1),
   AGENT varchar(255) not null,
   ROLE varchar(255),
   PARTICIPATIONSTATUSID bigint,
   COURSEOFFERINGUUID varchar(255),
   COURSESECTIONUUID varchar(255) not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   COURSEOFFERINGID bigint,
   COURSESECTIONID bigint
);
create table CM_COURSEOFFERINGSTATUS_T (
   COURSEOFFERINGSTATUSID bigint generated by default as identity (start with 1),
   AUTHORITY varchar(255) not null,
   DOMAIN varchar(255) not null,
   KEYWORD varchar(255) not null,
   DISPLAYNAME varchar(255),
   DESCRIPTION varchar(255),
   UUID varchar(255) not null,
   STATUS integer not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null
);
create table CM_COURSESECTIONTYPE_T (
   COURSESECTIONTYPEID bigint generated by default as identity (start with 1),
   AUTHORITY varchar(255) not null,
   DOMAIN varchar(255) not null,
   KEYWORD varchar(255) not null,
   DISPLAYNAME varchar(255),
   DESCRIPTION varchar(255),
   UUID varchar(255) not null,
   STATUS integer not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null
);
create table CM_COURSESECTIONSTATUS_T (
   COURSESECTIONSTATUSID bigint generated by default as identity (start with 1),
   AUTHORITY varchar(255) not null,
   DOMAIN varchar(255) not null,
   KEYWORD varchar(255) not null,
   DISPLAYNAME varchar(255),
   DESCRIPTION varchar(255),
   UUID varchar(255) not null,
   STATUS integer not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null
);
create table CM_CANONICALCOURSE_T (
   CANONICALCOURSEID bigint generated by default as identity (start with 1),
   TITLE varchar(255) not null,
   DESCRIPTION varchar(4000),
   COURSENUMBER varchar(255) not null,
   DEFAULTCREDITS varchar(255),
   TOPICS varchar(255),
   PREREQUISITE varchar(255),
   CANONICALCOURSESTATUSID bigint,
   EQUIVALENTS varchar(255),
   PARENTID varchar(255),
   UUID varchar(255) not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null
);
create table CM_SESSION_T (
   SESSIONID bigint generated by default as identity (start with 1),
   TITLE varchar(255) not null,
   ABBREVIATION varchar(255) not null,
   YEAR varchar(255) not null,
   ISCURRENT bit not null,
   UUID varchar(255) not null,
   SESSIONTYPEUUID varchar(255),
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null
);
create table CM_ENROLLMENTTYPE_T (
   ENROLLMENTTYPEID bigint generated by default as identity (start with 1),
   AUTHORITY varchar(255) not null,
   DOMAIN varchar(255) not null,
   KEYWORD varchar(255) not null,
   DISPLAYNAME varchar(255),
   DESCRIPTION varchar(255),
   UUID varchar(255) not null,
   STATUS integer not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null
);
create table CM_CANONICALCOURSESET_T (
   CANONICALCOURSESETID bigint generated by default as identity (start with 1),
   COURSESETUUID varchar(255) not null,
   CANONICALCOURSEUUID varchar(255) not null
);
create table CM_PARTICIPATIONSTATUS_T (
   PARTICIPATIONSTATUSID bigint generated by default as identity (start with 1),
   AUTHORITY varchar(255) not null,
   DOMAIN varchar(255) not null,
   KEYWORD varchar(255) not null,
   DISPLAYNAME varchar(255),
   DESCRIPTION varchar(255),
   UUID varchar(255) not null,
   STATUS integer not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null
);
create table CM_COURSESECTION_T (
   COURSESECTIONID bigint generated by default as identity (start with 1),
   TITLE varchar(255) not null,
   DESCRIPTION varchar(255),
   SECTIONNUMBER varchar(255) not null,
   MAXIMUMSTUDENTS integer,
   SESSIONID bigint,
   SCHEDULE varchar(4000),
   SECTIONEVENTS varchar(255),
   LOCATION varchar(4000),
   MEETINGTIME varchar(4000),
   COURSESECTIONSTATUSID bigint,
   COURSESECTIONTYPEID bigint,
   HOLDINGSECTION bit,
   ENROLLMENTSTATUSID bigint,
   COURSEOFFERINGUUID varchar(255) not null,
   PARENTSECTIONID bigint,
   UUID varchar(255) not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   ALLOWSELFREGISTRATION bit,
   COURSEOFFERINGID bigint
);
create table CM_COURSESET_T (
   COURSESETID bigint generated by default as identity (start with 1),
   TITLE varchar(255),
   CONTEXT varchar(255),
   UUID varchar(255) not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null
);
create table CM_SESSIONTYPE_T (
   SESSIONTYPEID bigint generated by default as identity (start with 1),
   AUTHORITY varchar(255) not null,
   DOMAIN varchar(255) not null,
   KEYWORD varchar(255) not null,
   DISPLAYNAME varchar(255),
   DESCRIPTION varchar(255),
   UUID varchar(255) not null,
   STATUS integer not null,
   LASTMODIFIEDBY varchar(255) not null,
   LASTMODIFIEDDATE timestamp not null,
   CREATEDBY varchar(255) not null,
   CREATEDDATE timestamp not null
);
alter table CM_ENROLLMENTRECORD_T add constraint FK371AA8DF6B67A391 foreign key (ENROLLMENTSTATUSID) references CM_ENROLLMENTSTATUS_T;
alter table CM_COURSEOFFERING_T add constraint FKD254CBEB8B4970AE foreign key (COURSEOFFERINGSTATUSID) references CM_COURSEOFFERINGSTATUS_T;
alter table CM_COURSEOFFERING_T add constraint FKD254CBEBCA525211 foreign key (SESSIONID) references CM_SESSION_T;
alter table CM_COURSEOFFERING_T add constraint FKD254CBEBA459A5D9 foreign key (ENROLLMENTTYPEID) references CM_ENROLLMENTTYPE_T;
alter table CM_COURSEOFFERING_T add constraint FKD254CBEB21961636 foreign key (COURSEOFFERINGTYPEID) references CM_COURSEOFFERINGTYPE_T;
alter table CM_PARTICIPATIONRECORD_T add constraint FKA9134DF2F65C8CAE foreign key (PARTICIPATIONSTATUSID) references CM_PARTICIPATIONSTATUS_T;
alter table CM_CANONICALCOURSE_T add constraint FKDD9E516F49D9D37C foreign key (CANONICALCOURSESTATUSID) references CM_CANONICALCOURSESTATUS_T;
alter table CM_COURSESECTION_T add constraint FKE6425DCA6B67A391 foreign key (ENROLLMENTSTATUSID) references CM_ENROLLMENTSTATUS_T;
alter table CM_COURSESECTION_T add constraint FKE6425DCACA525211 foreign key (SESSIONID) references CM_SESSION_T;
alter table CM_COURSESECTION_T add constraint FKE6425DCA1880BC9F foreign key (COURSESECTIONTYPEID) references CM_COURSESECTIONTYPE_T;
alter table CM_COURSESECTION_T add constraint FKE6425DCA722420D7 foreign key (COURSESECTIONSTATUSID) references CM_COURSESECTIONSTATUS_T;
alter table CM_COURSESECTION_T add constraint FKE6425DCAEA261936 foreign key (PARENTSECTIONID) references CM_COURSESECTION_T;
