alter table SYLLABUS_DATA_T drop constraint FK8AD134994FDCE067;
drop table SYLLABUS_DATA_T if exists;
drop table SYLLABUS_T if exists;
create table SYLLABUS_DATA_T (
   id bigint generated by default as identity (start with 1),
   lockId integer not null,
   asset longvarchar,
   position integer not null,
   title varchar(256),
   xview varchar(16),
   status varchar(64),
   emailNotification varchar(128),
   surrogateKey bigint
);
create table SYLLABUS_T (
   id bigint generated by default as identity (start with 1),
   lockId integer not null,
   userId varchar(36) not null,
   contextId varchar(36) not null,
   redirectURL varchar(512),
   unique (userId, contextId)
);
create index syllabus_position on SYLLABUS_DATA_T (position);
alter table SYLLABUS_DATA_T add constraint FK8AD134994FDCE067 foreign key (surrogateKey) references SYLLABUS_T;
create index syllabus_userId on SYLLABUS_T (userId);
create index syllabus_contextId on SYLLABUS_T (contextId);
