@\dev\sakai\deploy\src\sql\legacy\oracle\chef_announcement.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_assignment.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_calendar.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_chat.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\sakai_cluster.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_content.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_digest.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_discussion.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_dissertation.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_event.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_id.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_mailarchive.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_notification.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_preferences.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_presence.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_realm.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_session.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\chef_site.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\sakai_locks.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\sakai_alias.sql
@\dev\sakai\deploy\src\sql\legacy\oracle\sakai_user.sql
