-----------------------------------------------------------------------------
-- ANNOUNCEMENT_CHANNEL
-----------------------------------------------------------------------------

DROP TABLE IF EXISTS ANNOUNCEMENT_CHANNEL;

CREATE TABLE ANNOUNCEMENT_CHANNEL
(
    CHANNEL_ID VARCHAR (99) NOT NULL,
	NEXT_ID INT,
    XML LONG
);

CREATE UNIQUE INDEX ANNOUNCEMENT_CHANNEL_INDEX ON ANNOUNCEMENT_CHANNEL
(
	CHANNEL_ID
);

-----------------------------------------------------------------------------
-- ANNOUNCEMENT_MESSAGE
-----------------------------------------------------------------------------

DROP TABLE IF EXISTS ANNOUNCEMENT_MESSAGE;

CREATE TABLE ANNOUNCEMENT_MESSAGE (
       CHANNEL_ID           VARCHAR(99) NOT NULL,
       MESSAGE_ID           VARCHAR(32) NOT NULL,
       DRAFT                CHAR(1) NULL
                                   CHECK (DRAFT IN (1, 0)),
       PUBVIEW              CHAR(1) NULL
                                   CHECK (PUBVIEW IN (1, 0)),
       OWNER                VARCHAR (99) NULL,
       MESSAGE_DATE         DATETIME NOT NULL,
       XML                  LONG NULL
);


ALTER TABLE ANNOUNCEMENT_MESSAGE
       ADD  ( PRIMARY KEY (CHANNEL_ID, MESSAGE_ID) ) ;

--DROP INDEX XIF1ANNOUNCEMENT_MESSAGE ON ANNOUNCEMENT_MESSAGE;
--DROP INDEX IE_ANNC_MSG_CHANNEL ON ANNOUNCEMENT_MESSAGE;
--DROP INDEX IE_ANNC_MSG_ATTRIB ON ANNOUNCEMENT_MESSAGE;
--DROP INDEX IE_ANNC_MSG_DATE ON ANNOUNCEMENT_MESSAGE;
--DROP INDEX IE_ANNC_MSG_DATE_DESC ON ANNOUNCEMENT_MESSAGE;

CREATE INDEX IE_ANNC_MSG_CHANNEL ON ANNOUNCEMENT_MESSAGE
(
       CHANNEL_ID                     ASC
);

CREATE INDEX IE_ANNC_MSG_ATTRIB ON ANNOUNCEMENT_MESSAGE
(
       DRAFT                          ASC,
       PUBVIEW                        ASC,
       OWNER                          ASC
);

CREATE INDEX IE_ANNC_MSG_DATE ON ANNOUNCEMENT_MESSAGE
(
       MESSAGE_DATE                   ASC
);

CREATE INDEX IE_ANNC_MSG_DATE_DESC ON ANNOUNCEMENT_MESSAGE
(
       MESSAGE_DATE                   DESC
);

DESCRIBE ANNOUNCEMENT_CHANNEL;

DESCRIBE ANNOUNCEMENT_MESSAGE;

-- to convert from pre Sakai 2.0.6 (also add the indexes)
--ALTER TABLE ANNOUNCEMENT_MESSAGE ADD DRAFT CHAR (1);
--ALTER TABLE ANNOUNCEMENT_MESSAGE ADD PUBVIEW CHAR (1);
--ALTER TABLE ANNOUNCEMENT_MESSAGE ADD OWNER VARCHAR (99);

