DROP TABLE ASSESSMENTBASE CASCADE CONSTRAINTS
;

CREATE TABLE ASSESSMENTBASE (
  ID                       INTEGER         NOT NULL ,
  ISTEMPLATE	           INTEGER         NOT NULL ,
  PARENTID                 INTEGER ,
  TITLE                    VARCHAR(255) ,
  DESCRIPTION              LONG VARCHAR ,
  COMMENTS                 VARCHAR(255) ,
  ASSESSMENTTEMPLATEID     INTEGER ,
  TYPEID                   VARCHAR(36),
  INSTRUCTORNOTIFICATION   INTEGER ,
  TESTEENOTIFICATION       INTEGER ,
  MULTIPARTALLOWED         INTEGER ,
  STATUS                   INTEGER         NOT NULL ,
  CREATEDBY                VARCHAR(36)           NOT NULL ,
  CREATEDDATE              DATETIME          NOT NULL ,
  LASTMODIFIEDBY           VARCHAR(36)           NOT NULL ,
  LASTMODIFIEDDATE         DATETIME          NOT NULL ,
  CONSTRAINT PK_ASSESSMENT PRIMARY KEY (ID)
)
;

DROP TABLE ASSESSMENTACCESSCONTROL CASCADE CONSTRAINTS
;
CREATE TABLE ASSESSMENTACCESSCONTROL (
  ASSESSMENTID            INTEGER         NOT NULL ,
  UNLIMITEDSUBMISSIONS      INTEGER ,
  SUBMISSIONSALLOWED      INTEGER ,
  SUBMISSIONSSAVED        INTEGER ,
  ASSESSMENTFORMAT        INTEGER ,
  BOOKMARKINGITEM         INTEGER ,
  TIMELIMIT               INTEGER ,
  TIMEDASSESSMENT         INTEGER ,
  RETRYALLOWED            INTEGER ,
  LATEHANDLING            INTEGER ,
  STARTDATE               DATETIME,
  DUEDATE                 DATETIME,
  SCOREDATE               DATETIME,
  FEEDBACKDATE            DATETIME,
  RETRACTDATE             DATETIME,
  AUTOSUBMIT              INTEGER,
  ITEMNAVIGATION          INTEGER,
  ITEMNUMBERING           INTEGER,
  SUBMISSIONMESSAGE       LONG VARCHAR,
  RELEASETO               VARCHAR(255),
  USERNAME               VARCHAR(255),
  PASSWORD               VARCHAR(255),
  FINALPAGEURL           VARCHAR(1023),
  CONSTRAINT FK_ACCESS_ASSESSMENTID FOREIGN KEY (ASSESSMENTID) REFERENCES ASSESSMENTBASE(ID)
)
;

DROP TABLE ASSESSMENTEVALUATIONMODEL CASCADE CONSTRAINTS
;
CREATE TABLE ASSESSMENTEVALUATIONMODEL (
  ASSESSMENTID            INTEGER         NOT NULL ,
  EVALUATIONCOMPONENTS    VARCHAR(255),
  SCORINGTYPE             INTEGER ,
  NUMERICMODELID          VARCHAR(36),
  FIXEDTOTALSCORE         INTEGER ,
  GRADEAVAILABLE          INTEGER ,
  ISSTUDENTIDPUBLIC       INTEGER ,
  ANONYMOUSGRADING        INTEGER ,
  AUTOSCORING             INTEGER ,
  TOGRADEBOOK             INTEGER ,
  CONSTRAINT FK_EVAL_ASSESSMENTID FOREIGN KEY (ASSESSMENTID) REFERENCES ASSESSMENTBASE(ID)
)
;

DROP TABLE ASSESSMENTFEEDBACK CASCADE CONSTRAINTS
;
CREATE TABLE ASSESSMENTFEEDBACK (
  ASSESSMENTID            INTEGER         NOT NULL ,
  FEEDBACKDELIVERY        INTEGER,
  EDITCOMPONENTS          INTEGER,
  SHOWQUESTIONTEXT        INTEGER,
  SHOWSTUDENTRESPONSE        INTEGER,
  SHOWCORRECTRESPONSE        INTEGER,
  SHOWSTUDENTSCORE        INTEGER,
  SHOWQUESTIONLEVELFEEDBACK        INTEGER,
  SHOWSELECTIONLEVELFEEDBACK        INTEGER,
  SHOWGRADERCOMMENTS        INTEGER,
  SHOWSTATISTICS        INTEGER,
  CONSTRAINT FK_FB_ASSESSMENTID FOREIGN KEY (ASSESSMENTID) REFERENCES ASSESSMENTBASE(ID)
)
;

DROP TABLE ASSESSMENTMETADATA CASCADE CONSTRAINTS
;
CREATE TABLE ASSESSMENTMETADATA (
  ASSESSMENTMETADATAID  INTEGER        NOT NULL ,
  ASSESSMENTID           INTEGER          NOT NULL,
  LABEL            VARCHAR(255)  NOT NULL,
  ENTRY            VARCHAR(255) ,
  CONSTRAINT PK_ASSESSMENTMETADATA PRIMARY KEY (ASSESSMENTMETADATAID),
  CONSTRAINT FK_ASSESSMENTMETADATA_ID FOREIGN KEY (ASSESSMENTID) REFERENCES ASSESSMENTBASE(ID)
)
;

DROP TABLE SECUREDIPADDRESS CASCADE CONSTRAINTS
;
CREATE TABLE SECUREDIPADDRESS (
  IPADDRESSID  INTEGER        NOT NULL ,
  ASSESSMENTID           INTEGER          NOT NULL,
  HOSTNAME            VARCHAR(255) ,
  IPADDRESS            VARCHAR(255) ,
  CONSTRAINT PK_SECUREDIPADDRESS PRIMARY KEY (IPADDRESSID),
  CONSTRAINT FK_SECUREDIPADDRESS_ID FOREIGN KEY (ASSESSMENTID) REFERENCES ASSESSMENTBASE(ID)
)
;

DROP TABLE SECTION CASCADE CONSTRAINTS
;

CREATE TABLE SECTION (
  SECTIONID        INTEGER         NOT NULL ,
  ASSESSMENTID     INTEGER         NOT NULL ,
  DURATION         INTEGER          ,
  SEQUENCE         INTEGER          ,
  TITLE            LONG VARCHAR ,
  DESCRIPTION      LONG VARCHAR ,
  TYPEID           VARCHAR(36),
  STATUS           INTEGER         NOT NULL ,
  CREATEDBY        VARCHAR(36)           NOT NULL ,
  CREATEDDATE      DATETIME          NOT NULL ,
  LASTMODIFIEDBY    VARCHAR(36)           NOT NULL ,
  LASTMODIFIEDDATE  DATETIME          NOT NULL ,
  CONSTRAINT PK_ISECTION PRIMARY KEY (SECTIONID)
)
;
