DROP TABLE PUBLISHEDASSESSMENT CASCADE CONSTRAINTS;

CREATE TABLE PUBLISHEDASSESSMENT (
  ID                       INTEGER          NOT NULL ,
  ASSESSMENTID             INTEGER  ,
  TITLE                    VARCHAR(255) ,
  DESCRIPTION              LONG VARCHAR ,
  COMMENTS                 VARCHAR(255) ,
  ASSESSMENTTEMPLATEID     INTEGER  ,
  TYPEID                   VARCHAR(36),
  INSTRUCTORNOTIFICATION   INTEGER ,
  TESTEENOTIFICATION       INTEGER ,
  MULTIPARTALLOWED         INTEGER ,
  STATUS                   INTEGER          NOT NULL ,
  CREATEDBY                VARCHAR(36)           NOT NULL ,
  CREATEDDATE              DATETIME          NOT NULL ,
  LASTMODIFIEDBY           VARCHAR(36)           NOT NULL ,
  LASTMODIFIEDDATE         DATETIME          NOT NULL ,
  CONSTRAINT PK_PUBLISHEDASSESSMENT PRIMARY KEY (ID)
);

DROP TABLE PUBLISHEDACCESSCONTROL CASCADE CONSTRAINTS;

CREATE TABLE PUBLISHEDACCESSCONTROL (
  ASSESSMENTID            INTEGER          NOT NULL ,
  UNLIMITEDSUBMISSIONS    INTEGER ,
  SUBMISSIONSALLOWED      INTEGER ,
  SUBMISSIONSSAVED        INTEGER ,
  ASSESSMENTFORMAT        INTEGER ,
  BOOKMARKINGITEM         INTEGER ,
  TIMELIMIT               INTEGER ,
  TIMEDASSESSMENT         INTEGER ,
  RETRYALLOWED            INTEGER ,
  LATEHANDLING            INTEGER ,
  STARTDATE               DATETIME,
  DUEDATE                 DATETIME,
  SCOREDATE               DATETIME,
  FEEDBACKDATE            DATETIME,
  RETRACTDATE             DATETIME,
  AUTOSUBMIT              INTEGER,
  ITEMNAVIGATION          INTEGER,
  ITEMNUMBERING           INTEGER,
  SUBMISSIONMESSAGE       LONG VARCHAR,
  RELEASETO               VARCHAR(255),
  USERNAME               VARCHAR(255),
  PASSWORD               VARCHAR(255),
  FINALPAGEURL           VARCHAR(1023),
  CONSTRAINT FK_PUBLISHED_ACCESS_ID FOREIGN KEY (ASSESSMENTID) REFERENCES PUBLISHEDASSESSMENT(ID)
);

DROP TABLE PUBLISHEDEVALUATIONMODEL CASCADE CONSTRAINTS;

CREATE TABLE PUBLISHEDEVALUATIONMODEL (
  ASSESSMENTID            INTEGER          NOT NULL ,
  EVALUATIONCOMPONENTS    VARCHAR(255),
  SCORINGTYPE             INTEGER ,
  NUMERICMODELID          VARCHAR(36),
  FIXEDTOTALSCORE         INTEGER ,
  GRADEAVAILABLE          INTEGER ,
  ISSTUDENTIDPUBLIC       INTEGER ,
  ANONYMOUSGRADING        INTEGER ,
  AUTOSCORING             INTEGER ,
  TOGRADEBOOK             INTEGER ,
  CONSTRAINT FK_PUBLISHED_EVAL_ID FOREIGN KEY (ASSESSMENTID) REFERENCES PUBLISHEDASSESSMENT(ID)
);

CREATE TABLE PUBLISHEDFEEDBACK (
  ASSESSMENTID            INTEGER         NOT NULL ,
  FEEDBACKDELIVERY        INTEGER,
  EDITCOMPONENTS          INTEGER,
  SHOWQUESTIONTEXT        INTEGER,
  SHOWSTUDENTRESPONSE        INTEGER,
  SHOWCORRECTRESPONSE        INTEGER,
  SHOWSTUDENTSCORE        INTEGER,
  SHOWQUESTIONLEVELFEEDBACK        INTEGER,
  SHOWSELECTIONLEVELFEEDBACK        INTEGER,
  SHOWGRADERCOMMENTS        INTEGER,
  SHOWSTATISTICS        INTEGER,
  CONSTRAINT FK_PUBLISHED_FB_ID FOREIGN KEY (ASSESSMENTID) REFERENCES PUBLISHEDASSESSMENT(ID)
);

DROP TABLE PUBLISHEDMETADATA CASCADE CONSTRAINTS;

CREATE TABLE PUBLISHEDMETADATA (
  ASSESSMENTMETADATAID  INTEGER         NOT NULL ,
  ASSESSMENTID           INTEGER           NOT NULL,
  LABEL            VARCHAR(255)  NOT NULL,
  ENTRY            VARCHAR(255) ,
  CONSTRAINT PK_PUBLISHEDMETADATA PRIMARY KEY (ASSESSMENTMETADATAID),
  CONSTRAINT FK_PUBLISHEDMETADATA_ID FOREIGN KEY (ASSESSMENTID) REFERENCES PUBLISHEDASSESSMENT(ID)
);

DROP TABLE PUBLISHEDSECUREDIPADDRESS CASCADE CONSTRAINTS;

CREATE TABLE PUBLISHEDSECUREDIPADDRESS (
  IPADDRESSID  INTEGER        NOT NULL ,
  ASSESSMENTID           INTEGER          NOT NULL,
  HOSTNAME            VARCHAR(255),
  IPADDRESS            VARCHAR(255) ,
  CONSTRAINT PK_PUBLISHEDIPADDRESS PRIMARY KEY (IPADDRESSID),
  CONSTRAINT FK_PUBLISHEDIPADDRESS_ID FOREIGN KEY (ASSESSMENTID) REFERENCES PUBLISHEDASSESSMENT(ID)
);


DROP TABLE PUBLISHEDSECTION CASCADE CONSTRAINTS;

CREATE TABLE PUBLISHEDSECTION (
  SECTIONID        INTEGER          NOT NULL ,
  ASSESSMENTID     INTEGER          NOT NULL ,
  DURATION         INTEGER           ,
  SEQUENCE         INTEGER           ,
  TITLE            LONG VARCHAR ,
  DESCRIPTION      LONG VARCHAR ,
  TYPEID           VARCHAR(36)           NOT NULL ,
  STATUS           INTEGER          NOT NULL ,
  CREATEDBY        VARCHAR(36)           NOT NULL ,
  CREATEDDATE      DATETIME          NOT NULL ,
  LASTMODIFIEDBY    VARCHAR(36)           NOT NULL ,
  LASTMODIFIEDDATE  DATETIME          NOT NULL ,
  CONSTRAINT PK_PUBLISHEDSECTION PRIMARY KEY (SECTIONID)
);
