DROP TABLE PUBLISHEDITEM CASCADE CONSTRAINTS;

CREATE TABLE PUBLISHEDITEM (
  ITEMID           INTEGER          NOT NULL ,
  SECTIONID           INTEGER          NOT NULL ,
  ITEMIDSTRING     VARCHAR(36) ,
  SEQUENCE         INTEGER           ,
  DURATION         INTEGER           ,
  TRIESALLOWED         INTEGER           ,
  INSTRUCTION      LONG VARCHAR ,
  DESCRIPTION      LONG VARCHAR ,
  TYPEID           VARCHAR(36)           NOT NULL ,
  GRADE            VARCHAR(80) ,
  SCORE            FLOAT,
  HINT             LONG VARCHAR ,
  HASRATIONALE     VARCHAR(1)          ,
  STATUS           INTEGER          NOT NULL ,
  CREATEDBY        VARCHAR(36)           NOT NULL ,
  CREATEDDATE      DATETIME          NOT NULL ,
  LASTMODIFIEDBY    VARCHAR(36)           NOT NULL ,
  LASTMODIFIEDDATE  DATETIME          NOT NULL ,
  CONSTRAINT PK_PUBLISHEDITEM PRIMARY KEY (ITEMID)
);

DROP TABLE PUBLISHEDITEMTEXT CASCADE CONSTRAINTS;

CREATE TABLE PUBLISHEDITEMTEXT (
  ITEMTEXTID  INTEGER        NOT NULL   ,
  ITEMID      INTEGER           NOT NULL,
  SEQUENCE    INTEGER            NOT NULL ,
  TEXT        LONG VARCHAR ,
  CONSTRAINT PK_PUBLISHEDITEMTEXT PRIMARY KEY (ITEMTEXTID),
  CONSTRAINT FK_PUBLISHEDITEMTEXT_ID FOREIGN KEY (ITEMID) REFERENCES PUBLISHEDITEM(ITEMID)
);

DROP TABLE PUBLISHEDITEMMETADATA CASCADE CONSTRAINTS;

CREATE TABLE PUBLISHEDITEMMETADATA (
  ITEMMETADATAID  INTEGER         NOT NULL ,
  ITEMID           INTEGER           NOT NULL,
  LABEL            VARCHAR(255)  NOT NULL,
  ENTRY            VARCHAR(255) ,
  CONSTRAINT PK_PUBLISHEDITEMMETADATA PRIMARY KEY (ITEMMETADATAID),
  CONSTRAINT FK_PUBLISHEDITEMMETADATA_ID FOREIGN KEY (ITEMID) REFERENCES PUBLISHEDITEM(ITEMID)
);

DROP TABLE PUBLISHEDANSWER CASCADE CONSTRAINTS;

CREATE TABLE PUBLISHEDANSWER (
  ANSWERID    INTEGER            NOT NULL ,
  ITEMTEXTID  INTEGER            NOT NULL ,
  ITEMID      INTEGER            NOT NULL ,
  TEXT        LONG VARCHAR,
  SEQUENCE    INTEGER           ,
  LABEL       VARCHAR(20)  ,
  ISCORRECT   VARCHAR(1) ,
  GRADE            VARCHAR(80) ,
  SCORE            FLOAT ,
  CONSTRAINT PK_PUBLISHEDANSWER PRIMARY KEY (ANSWERID),
  CONSTRAINT FK_PUBLISHEDANSWER_TEXTID FOREIGN KEY (ITEMTEXTID) REFERENCES PUBLISHEDITEMTEXT(ITEMTEXTID),
  CONSTRAINT FK_PUBLISHEDANSWER_ID FOREIGN KEY (ITEMID) REFERENCES PUBLISHEDITEM(ITEMID)
);

DROP TABLE PUBLISHEDITEMFEEDBACK CASCADE CONSTRAINTS;

CREATE TABLE PUBLISHEDITEMFEEDBACK (
  ITEMFEEDBACKID     INTEGER            NOT NULL ,
  ITEMID             INTEGER            NOT NULL ,
  TYPEID    VARCHAR(36) NOT NULL,
  TEXT  LONG VARCHAR ,
  CONSTRAINT PK_PUBLISHEDITEMFEEDBACK PRIMARY KEY (ITEMFEEDBACKID),
  CONSTRAINT FK_PUBLISHEDITEMFEEDBACK_ID FOREIGN KEY (ITEMID) REFERENCES PUBLISHEDITEM(ITEMID)
);

DROP TABLE PUBLISHEDANSWERFEEDBACK CASCADE CONSTRAINTS;

CREATE TABLE PUBLISHEDANSWERFEEDBACK (
  ANSWERFEEDBACKID     INTEGER            NOT NULL ,
  ANSWERID             INTEGER            NOT NULL ,
  TYPEID    VARCHAR(36) NOT NULL,
  TEXT  LONG VARCHAR ,
  CONSTRAINT PK_PUBANSWERFEEDBACK PRIMARY KEY (ANSWERFEEDBACKID),
  CONSTRAINT FK_PUBANSWERFEEDBACK_ANSWERID FOREIGN KEY (ANSWERID) REFERENCES PUBLISHEDANSWER(ANSWERID)
);

