DROP TABLE ASSESSMENTGRADINGDATA CASCADE CONSTRAINTS;

CREATE TABLE ASSESSMENTGRADINGDATA(
   ASSESSMENTGRADINGID	    INTEGER    NOT NULL,
   PUBLISHEDASSESSMENTID           INTEGER          NOT NULL ,
   AGENTID           VARCHAR(36)         NOT NULL ,
   SUBMITTEDDATE   DATETIME     NOT NULL,
   ISLATE           INTEGER          NOT NULL ,
   FORGRADE           INTEGER          NOT NULL ,
   TOTALAUTOSCORE            FLOAT,
   TOTALOVERRIDESCORE            FLOAT,
   FINALSCORE            FLOAT,
   COMMENTS   LONG VARCHAR,
   GRADEDBY   VARCHAR(36),
   GRADEDDATE DATETIME ,
   STATUS           INTEGER          NOT NULL ,
   ATTEMPTDATE DATETIME ,
   TIMEELAPSED           INTEGER,
   CONSTRAINT PK_ASSESSMENTGRADING PRIMARY KEY (ASSESSMENTGRADINGID),
   CONSTRAINT FK_ASSESSMENTGRADING_PUBASSID FOREIGN KEY (PUBLISHEDASSESSMENTID) REFERENCES PUBLISHEDASSESSMENT(ID)
);

DROP TABLE ITEMGRADINGDATA CASCADE CONSTRAINTS;

CREATE TABLE ITEMGRADINGDATA(
   ITEMGRADINGID	    INTEGER    NOT NULL,
   ASSESSMENTGRADINGID	    INTEGER    NOT NULL,
   PUBLISHEDITEMID           INTEGER          NOT NULL ,
   PUBLISHEDITEMTEXTID           INTEGER          NOT NULL ,
   AGENTID           VARCHAR(36)           NOT NULL ,
   SUBMITTEDDATE   DATETIME NOT NULL,
   PUBLISHEDANSWERID           INTEGER ,
   RATIONALE    LONG VARCHAR,
   ANSWERTEXT    LONG VARCHAR,
   AUTOSCORE            FLOAT,
   OVERRIDESCORE            FLOAT,
   COMMENTS   LONG VARCHAR,
   GRADEDBY   VARCHAR(36),
   GRADEDDATE DATETIME ,
   REVIEW INTEGER,
   CONSTRAINT PK_ITEMGRADING PRIMARY KEY (ITEMGRADINGID),
   CONSTRAINT FK_ITEMGRADING_ASSID FOREIGN KEY (ASSESSMENTGRADINGID) REFERENCES ASSESSMENTGRADINGDATA(ASSESSMENTGRADINGID),
   CONSTRAINT FK_ITEMGRADING_ITEMID FOREIGN KEY (PUBLISHEDITEMID) REFERENCES PUBLISHEDITEM(ITEMID),
   CONSTRAINT FK_ITEMGRADING_ITEMTEXTID FOREIGN KEY (PUBLISHEDITEMTEXTID) REFERENCES PUBLISHEDITEMTEXT(ITEMTEXTID)
);

DROP TABLE ASSESSMENTGRADINGSUMMARY CASCADE CONSTRAINTS;

CREATE TABLE ASSESSMENTGRADINGSUMMARY(
   ASSESSMENTGRADINGSUMMARYID	    INTEGER    NOT NULL,
   PUBLISHEDASSESSMENTID           INTEGER          NOT NULL ,
   AGENTID           VARCHAR(36)           NOT NULL ,
   TOTALSUBMITTED  INTEGER ,
   TOTALSUBMITTEDFORGRADE  INTEGER ,
   LASTSUBMITTEDASSESSMENTGRADING  INTEGER ,
   LASTSUBMITTEDDATE   DATETIME,
   LASTSUBMITTEDASSESSMENTISLATE  INTEGER ,
   SUMOF_AUTOSCOREFORGRADE    FLOAT,
   AVERAGE_AUTOSCOREFORGRADE    FLOAT,
   HIGHEST_AUTOSCOREFORGRADE    FLOAT,
   LOWEST_AUTOSCOREFORGRADE    FLOAT,
   LAST_AUTOSCOREFORGRADE    FLOAT,
   SUMOF_OVERRIDESCOREFORGRADE    FLOAT,
   AVERAGE_OVERRIDESCOREFORGRADE    FLOAT,
   HIGHEST_OVERRIDESCOREFORGRADE    FLOAT,
   LOWEST_OVERRIDESCOREFORGRADE    FLOAT,
   LAST_OVERRIDESCOREFORGRADE    FLOAT,
   SCORINGTYPE  INTEGER ,
   ACCEPTEDASSESSMENTGRADING  INTEGER ,
   ACCEPTEDASSESSMENTISLATE  INTEGER ,
   FINALASSESSMENTSCORE    FLOAT,
   FEEDTOGRADEBOOK           INTEGER ,
   CONSTRAINT PK_ASSGRADINGSUMMARY PRIMARY KEY (ASSESSMENTGRADINGSUMMARYID),
   CONSTRAINT FK_ASSGRADINGSUMMARY_PUBASSID FOREIGN KEY (PUBLISHEDASSESSMENTID) REFERENCES PUBLISHEDASSESSMENT(ID)
);

commit;
