DROP TABLE FUNCTIONDATA CASCADE CONSTRAINTS;

CREATE TABLE FUNCTIONDATA (
  FUNCTIONID  VARCHAR(36)        NOT NULL   ,
  REFERENCENAME    VARCHAR(255) NOT NULL,
  DISPLAYNAME    VARCHAR(255) ,
  DESCRIPTION    LONG VARCHAR ,
  FUNCTIONTYPEID  VARCHAR(36) ,
  CONSTRAINT PK_FUNCTIONDATA PRIMARY KEY (FUNCTIONID)
);

commit;
INSERT INTO FUNCTIONDATA ("FUNCTIONID","REFERENCENAME","DISPLAYNAME","DESCRIPTION", "FUNCTIONTYPEID")
    VALUES(1,'take.published.assessment', 'Take Assessment','Take Assessment','81');
INSERT INTO FUNCTIONDATA ("FUNCTIONID","REFERENCENAME","DISPLAYNAME","DESCRIPTION", "FUNCTIONTYPEID")
    VALUES(2,'view.published.assessment', 'View Assessment','View Assessment','81');
INSERT INTO FUNCTIONDATA ("FUNCTIONID","REFERENCENAME","DISPLAYNAME","DESCRIPTION", "FUNCTIONTYPEID")
    VALUES(3,'submit.assessment.forgrade','Submit Assessment', 'Submit Assessment','81');
INSERT INTO FUNCTIONDATA ("FUNCTIONID","REFERENCENAME","DISPLAYNAME","DESCRIPTION", "FUNCTIONTYPEID")
    VALUES(4,'submit.assessment', 'Submit Assessment For Grade','Submit Assessment For Grade','81');
commit;



DROP TABLE QUALIFIERDATA CASCADE CONSTRAINTS;

CREATE TABLE QUALIFIERDATA (
  QUALIFIERID  VARCHAR(36)        NOT NULL ,
  REFERENCENAME    VARCHAR(255) ,
  DISPLAYNAME    VARCHAR(255) ,
  DESCRIPTION    LONG VARCHAR ,
  QUALIFIERTYPEID  VARCHAR(36) ,
  CONSTRAINT PK_QUALIFIERDATA PRIMARY KEY (QUALIFIERID)
);

commit;

INSERT INTO QUALIFIERDATA ("QUALIFIERID","REFERENCENAME","DISPLAYNAME","DESCRIPTION", "QUALIFIERTYPEID")
    VALUES(23,'201','assessment title', 'This assessment is #23','101');
INSERT INTO QUALIFIERDATA ("QUALIFIERID","REFERENCENAME","DISPLAYNAME","DESCRIPTION", "QUALIFIERTYPEID")
    VALUES(24,'202','assessment title', 'This assessment is #24','101');
commit;



DROP TABLE QUALIFIERHIERARCHYDATA;

CREATE TABLE QUALIFIERHIERARCHYDATA (
        CHILDID      VARCHAR(36),
        PARENTID     VARCHAR(36),
  CONSTRAINT FK_QUALIFIERHIERARCHY_CHILDID FOREIGN KEY (CHILDID) REFERENCES QUALIFIERDATA(QUALIFIERID),
  CONSTRAINT FK_QUALIFIERHIERARCHY_PARENTID FOREIGN KEY (PARENTID) REFERENCES QUALIFIERDATA(QUALIFIERID)
);

commit;

DROP TABLE AUTHORIZATIONDATA CASCADE CONSTRAINTS;

CREATE TABLE AUTHORIZATIONDATA (
  AGENTID          VARCHAR(36)   NOT NULL ,
  FUNCTIONID       VARCHAR(36)   NOT NULL ,
  QUALIFIERID      VARCHAR(36) NOT NULL,
  EFFECTIVEDATE      DATETIME    ,
  EXPIRATIONDATE      DATETIME    ,
  LASTMODIFIEDBY    VARCHAR(36)      NOT NULL ,
  LASTMODIFIEDDATE  DATETIME          NOT NULL ,
  ISEXPLICIT       VARCHAR(1)  ,
  CONSTRAINT FK_AUTHORIZATION_FUNCTIONID FOREIGN KEY (FUNCTIONID) REFERENCES FUNCTIONDATA(FUNCTIONID),
  CONSTRAINT FK_AUTHORIZATION_QUALIFIERID FOREIGN KEY (QUALIFIERID) REFERENCES QUALIFIERDATA(QUALIFIERID)
);

commit;

INSERT INTO AUTHORIZATIONDATA ("AGENTID", "FUNCTIONID", "QUALIFIERID",
   "EFFECTIVEDATE", "EXPIRATIONDATE", "LASTMODIFIEDBY", "LASTMODIFIEDDATE","ISEXPLICIT")
   VALUES('2', '1', '23', SYSDATE, NULL, '2',SYSDATE,'1');
commit;

