--create default template
INSERT INTO ASSESSMENTBASE ("ID" ,"ISTEMPLATE" ,
    "PARENTID" ,"TITLE" ,"DESCRIPTION" ,"COMMENTS" ,
    "ASSESSMENTTEMPLATEID" ,"TYPEID" ,"INSTRUCTORNOTIFICATION" ,
    "TESTEENOTIFICATION" ,"MULTIPARTALLOWED" ,"STATUS" ,
    "CREATEDBY" ,"CREATEDDATE" ,"LASTMODIFIEDBY" ,
    "LASTMODIFIEDDATE" )
    VALUES (1 ,1 ,0 ,'Default Template' ,'' ,'comments' , NULL
    ,'42' ,1 ,1 ,1 ,1 ,'admin' ,SYSDATE ,'admin' ,SYSDATE  )
/
INSERT INTO ASSESSMENTEVALUATIONMODEL ("ASSESSMENTID" ,
    "EVALUATIONCOMPONENTS" ,"SCORINGTYPE" ,"NUMERICMODELID" ,
    "FIXEDTOTALSCORE" ,"GRADEAVAILABLE" ,"ISSTUDENTIDPUBLIC" ,
    "ANONYMOUSGRADING" ,"AUTOSCORING" ,"TOGRADEBOOK" )
    VALUES (1 ,'' ,1 ,'' , NULL , NULL , NULL ,1 , NULL ,1  )
/
INSERT INTO ASSESSMENTFEEDBACK ("ASSESSMENTID" ,
    "FEEDBACKDELIVERY" ,"SHOWQUESTIONTEXT" ,"SHOWSTUDENTRESPONSE"
    ,"SHOWCORRECTRESPONSE" ,"SHOWSTUDENTSCORE" ,
    "SHOWQUESTIONLEVELFEEDBACK" ,"SHOWSELECTIONLEVELFEEDBACK" ,
    "SHOWGRADERCOMMENTS" ,"SHOWSTATISTICS" ,"EDITCOMPONENTS" )
    VALUES (1 ,1 ,1 ,1 ,1 ,1 ,1 ,0 ,1 ,1 ,1  )
/
INSERT INTO ASSESSMENTACCESSCONTROL ("ASSESSMENTID" ,
    "SUBMISSIONSALLOWED" ,"SUBMISSIONSSAVED" ,"ASSESSMENTFORMAT" ,
    "BOOKMARKINGITEM" ,"TIMELIMIT" ,"TIMEDASSESSMENT" ,
    "RETRYALLOWED" ,"LATEHANDLING" ,"STARTDATE" ,"DUEDATE" ,
    "SCOREDATE" ,"FEEDBACKDATE" ,"RETRACTDATE" ,"AUTOSUBMIT" ,
    "ITEMNAVIGATION" ,"ITEMNUMBERING" ,"SUBMISSIONMESSAGE" ,
    "RELEASETO" ,"USERNAME" ,"PASSWORD" ,"FINALPAGEURL" ,
    "UNLIMITEDSUBMISSIONS" )
    VALUES (1 ,1 ,1 ,1 , NULL , NULL , NULL , NULL ,1 ,
    TO_DATE('', 'dd-Mon-yyyy HH:MI:SS AM') ,TO_DATE('',
    'dd-Mon-yyyy HH:MI:SS AM') ,TO_DATE('', 'dd-Mon-yyyy HH:MI:SS
    AM') ,TO_DATE('', 'dd-Mon-yyyy HH:MI:SS AM') ,TO_DATE('',
    'dd-Mon-yyyy HH:MI:SS AM') ,1 ,2 ,1 ,'' ,'' ,'' ,'' ,'' ,
    NULL  )
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(1, 1, 'finalPageURL_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(2, 1, 'anonymousRelease_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(3, 1, 'dueDate_isInstructorEditable', 'true')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(4, 1, 'description_isInstructorEditable', 'true')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(5, 1, 'metadataQuestions_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(6, 1, 'bgImage_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(7, 1, 'feedbackComponents_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(8, 1, 'retractDate_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(9, 1, 'feedbackType_isInstructorEditable', 'true')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(10, 1, 'timedAssessmentAutoSubmit_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(11, 1, 'toGradebook_isInstructorEditablee', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(12, 1, 'displayChunking_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(13, 1, 'recordedScore_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(14, 1, 'authenticatedRelease_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(15, 1, 'displayNumbering_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(16, 1, 'submissionMessage_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(17, 1, 'releaseDate_isInstructorEditable', 'true')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(18, 1, 'assessmentAuthor_isInstructorEditable', 'true')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(19, 1, 'passwordRequired_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(20, 1, 'author', '')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(21, 1, 'submissionModel_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(22, 1, 'ipAccessType_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(23, 1, 'timedAssessment_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(24, 1, 'metadataAssess_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(25, 1, 'bgColor_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(26, 1, 'testeeIdentity_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(27, 1, 'templateInfo_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(28, 1, 'itemAccessType_isInstructorEditable', 'false')
/
INSERT INTO ASSESSMENTMETADATA ("ASSESSMENTMETADATAID", "ASSESSMENTID","LABEL",
    "ENTRY")
    VALUES(29, 1, 'lateHandling_isInstructorEditable', 'true')
/
commit;