create table sam_gradingSummary_t (
   assessmentGradingSummaryId bigint generated by default as identity (start with 1),
   publishedAssessmentId bigint not null,
   agentId varchar(36) not null,
   totalSubmitted integer,
   totalSubmittedForGrade integer,
   lastSubmittedDate datetime,
   lastSubmittedAssessmentIsLate integer not null,
   sumOf_autoScoreForGrade float,
   average_autoScoreForGrade float,
   highest_autoScoreForGrade float,
   lowest_autoScoreForGrade float,
   last_autoScoreForGrade float,
   sumOf_overrideScoreForGrade float,
   average_overrideScoreForGrade float,
   highest_overrideScoreForGrade float,
   lowest_overrideScoreForGrade float,
   last_overrideScoreForGrade float,
   scoringType integer,
   acceptedAssessmentIsLate integer,
   finalAssessmentScore float,
   feedToGradeBook integer
);
create table sam_item_t (
   itemId bigint generated by default as identity (start with 1),
   sectionId bigint,
   itemIdString varchar(36),
   sequence integer,
   duration integer,
   triesAllowed integer,
   instruction varchar(4000),
   description varchar(4000),
   typeId varchar(36) not null,
   grade varchar(80),
   score float,
   hint varchar(4000),
   hasRationale varchar(1),
   status integer not null,
   createdBy varchar(36) not null,
   createdDate datetime not null,
   lastModifiedBy varchar(36) not null,
   lastModifiedDate datetime not null
);
create table sam_publishedItem_t (
   itemId bigint generated by default as identity (start with 1),
   sectionId bigint not null,
   itemIdString varchar(36),
   sequence integer,
   duration integer,
   triesAllowed integer,
   instruction varchar(4000),
   description varchar(4000),
   typeId varchar(36) not null,
   grade varchar(80),
   score float,
   hint varchar(4000),
   hasRationale varchar(1),
   status integer not null,
   createdBy varchar(36) not null,
   createdDate datetime not null,
   lastModifiedBy varchar(36) not null,
   lastModifiedDate datetime not null
);
create table sam_publishedItemMetaData_t (
   itemMetaDataId bigint generated by default as identity (start with 1),
   itemId bigint not null,
   label varchar(255) not null,
   entry varchar(255)
);
create table sam_publishedItemText_t (
   itemTextId bigint generated by default as identity (start with 1),
   itemId bigint not null,
   sequence integer not null,
   text varchar(4000)
);
create table sam_securedIP_t (
   ipAddressId bigint generated by default as identity (start with 1),
   assessmentId bigint not null,
   hostname varchar(255),
   ipAddress varchar(255)
);
create table sam_section_t (
   sectionId bigint generated by default as identity (start with 1),
   assessmentId bigint not null,
   duration integer,
   sequence integer,
   title varchar(255),
   description varchar(4000),
   typeId integer,
   status integer not null,
   createdBy varchar(36) not null,
   createdDate datetime not null,
   lastModifiedBy varchar(36) not null,
   lastModifiedDate datetime not null
);
create table sam_publishedItemFeedback_t (
   itemFeedbackId bigint generated by default as identity (start with 1),
   itemId bigint not null,
   typeId varchar(36) not null,
   text varchar(4000)
);
create table sam_media_t (
   mediaId bigint generated by default as identity (start with 1),
   itemGradingId bigint,
   media varbinary(255),
   fileSize integer,
   mimeType varchar(80),
   description varchar(4000),
   location varchar(255),
   filename varchar(255),
   isLink integer,
   isHtmlInline integer,
   status integer,
   createdBy varchar(36),
   createdDate datetime,
   lastModifiedBy varchar(36),
   lastModifiedDate datetime
);
create table sam_itemGrading_t (
   itemGradingId bigint generated by default as identity (start with 1),
   assessmentGradingId bigint not null,
   publishedItemId bigint not null,
   publishedItemTextId bigint not null,
   agentId varchar(36) not null,
   submittedDate datetime not null,
   publishedAnswerId bigint,
   rationale varchar(4000),
   answerText varchar(4000),
   autoScore float,
   overrideScore float,
   Comments varchar(4000),
   gradedBy varchar(36),
   gradedDate datetime,
   review integer
);
create table sam_questionPool_t (
   questionPoolId bigint generated by default as identity (start with 1),
   title varchar(255),
   description varchar(255),
   parentPoolId integer,
   ownerId varchar(255),
   organizationName varchar(255),
   dateCreated datetime,
   lastModifiedDate datetime,
   lastModifiedBy varchar(255),
   defaultAccessTypeId integer,
   objective varchar(255),
   keywords varchar(255),
   rubric varchar(4000),
   typeId integer,
   intellectualPropertyId integer
);
create table sam_publishedEvaluation_t (
   assessmentId bigint not null,
   evaluationComponents varchar(255),
   scoringType integer,
   numericModelId varchar(255),
   fixedTotalScore integer,
   gradeAvailable integer,
   isStudentIdPublic integer,
   anonymousGrading integer,
   autoScoring integer,
   toGradeBook integer,
   primary key (assessmentId)
);
create table sam_answerFeedback_t (
   answerFeedbackId bigint generated by default as identity (start with 1),
   answerId bigint not null,
   typeId varchar(36),
   text varchar(4000)
);
create table sam_publishedFeedback_t (
   assessmentId bigint not null,
   feedbackDelivery integer,
   editComponents integer,
   showQuestionText integer,
   showStudentResponse integer,
   showCorrectResponse integer,
   showStudentScore integer,
   showQuestionLevelFeedback integer,
   showSelectionLevelFeedback integer,
   showGraderComments integer,
   showStatistics integer,
   primary key (assessmentId)
);
create table sam_questionPoolItem_t (
   questionPoolId bigint not null,
   itemId varchar(255) not null,
   primary key (questionPoolId, itemId)
);
create table sam_publishedSecuredIP_t (
   ipAddressId bigint generated by default as identity (start with 1),
   assessmentId bigint not null,
   hostname varchar(255),
   ipAddress varchar(255)
);
create table sam_functionData_t (
   functionId bigint generated by default as identity (start with 1),
   referenceName varchar(255) not null,
   displayName varchar(255),
   description varchar(4000),
   functionTypeId varchar(4000)
);
create table sam_assessmentBase_t (
   id bigint generated by default as identity (start with 1),
   isTemplate varchar(255) not null,
   parentId integer,
   title varchar(255),
   description varchar(4000),
   comments varchar(4000),
   typeId varchar(36),
   instructorNotification integer,
   testeeNotification integer,
   multipartAllowed integer,
   status integer not null,
   createdBy varchar(36) not null,
   createdDate datetime not null,
   lastModifiedBy varchar(36) not null,
   lastModifiedDate datetime not null,
   assessmentTemplateId bigint
);
create table sam_publishedAssessment_t (
   id bigint generated by default as identity (start with 1),
   assessmentId bigint not null,
   title varchar(255),
   description varchar(4000),
   comments varchar(255),
   typeId varchar(36),
   instructorNotification integer,
   testeeNotification integer,
   multipartAllowed integer,
   status integer not null,
   createdBy varchar(36) not null,
   createdDate datetime not null,
   lastModifiedBy varchar(36) not null,
   lastModifiedDate datetime not null
);
create table sam_itemText_t (
   itemTextId bigint generated by default as identity (start with 1),
   itemId bigint not null,
   sequence integer not null,
   text varchar(4000)
);
create table sam_assessFeedback_t (
   assessmentId bigint not null,
   feedbackDelivery integer,
   editComponents integer,
   showQuestionText integer,
   showStudentResponse integer,
   showCorrectResponse integer,
   showStudentScore integer,
   showQuestionLevelFeedback integer,
   showSelectionLevelFeedback integer,
   showGraderComments integer,
   showStatistics integer,
   primary key (assessmentId)
);
create table sam_type_t (
   typeId bigint generated by default as identity (start with 1),
   authority varchar(255),
   domain varchar(255),
   keyword varchar(255),
   description varchar(4000),
   status integer not null,
   createdBy varchar(36) not null,
   createdDate datetime not null,
   lastModifiedBy varchar(36) not null,
   lastModifiedDate datetime not null
);
create table sam_publishedAccessControl_t (
   assessmentId bigint not null,
   unlimitedSubmissions integer,
   submissionsAllowed integer,
   submissionsSaved integer,
   assessmentFormat integer,
   bookMarkingItem integer,
   timeLimit integer,
   timedAssessment integer,
   retryAllowed integer,
   lateHandling integer,
   startDate datetime,
   dueDate datetime,
   scoreDate datetime,
   feedbackDate datetime,
   retractDate datetime,
   autoSubmit integer,
   itemNavigation integer,
   itemNumbering integer,
   submissionMessage varchar(4000),
   releaseTo varchar(255),
   username varchar(255),
   password varchar(255),
   finalPageUrl varchar(1023),
   primary key (assessmentId)
);
create table sam_publishedAnswerFeedback_t (
   answerFeedbackId bigint generated by default as identity (start with 1),
   answerId bigint not null,
   typeId varchar(36),
   text varchar(4000)
);
create table sam_assessEvaluation_t (
   assessmentId bigint not null,
   evaluationComponents varchar(255),
   scoringType integer,
   numericModelId varchar(255),
   fixedTotalScore integer,
   gradeAvailable integer,
   isStudentIdPublic integer,
   anonymousGrading integer,
   autoScoring integer,
   toGradeBook varchar(255),
   primary key (assessmentId)
);
create table sam_publishedAnswer_t (
   answerId bigint generated by default as identity (start with 1),
   itemTextId bigint not null,
   itemId bigint not null,
   text varchar(4000),
   sequence integer not null,
   label varchar(20),
   isCorrect varchar(1),
   grade varchar(80),
   score float
);
create table sam_authzData_t (
   id bigint generated by default as identity (start with 1),
   lockId integer not null,
   agentId varchar(255) not null,
   functionId varchar(255) not null,
   qualifierId varchar(255) not null,
   effectiveDate datetime,
   expirationDate datetime,
   lastModifiedBy varchar(36) not null,
   lastModifiedDate datetime not null,
   isExplicit integer,
   unique (agentId, functionId, qualifierId)
);
create table sam_qualifierData_t (
   qualifierId bigint generated by default as identity (start with 1),
   referenceName varchar(255) not null,
   displayName varchar(255),
   description varchar(4000),
   qualifierTypeId varchar(4000)
);
create table sam_assessmentGrading_t (
   assessmentGradingId bigint generated by default as identity (start with 1),
   publishedAssessmentId bigint not null,
   agentId varchar(36) not null,
   submittedDate datetime not null,
   isLate varchar(1) not null,
   forGrade integer not null,
   totalAutoScore float,
   totalOverrideScore float,
   finalScore float,
   comments varchar(4000),
   gradedBy varchar(36),
   gradedDate datetime,
   status integer not null,
   attemptDate datetime,
   timeElapsed integer
);
create table sam_publishedSection_t (
   sectionId bigint generated by default as identity (start with 1),
   assessmentId bigint not null,
   duration integer,
   sequence integer,
   title varchar(255),
   description varchar(4000),
   typeId integer not null,
   status integer not null,
   createdBy varchar(36) not null,
   createdDate datetime not null,
   lastModifiedBy varchar(36) not null,
   lastModifiedDate datetime not null
);
create table sam_publishedMetaData_t (
   assessmentMetaDataId bigint generated by default as identity (start with 1),
   assessmentId bigint not null,
   label varchar(255) not null,
   entry varchar(255)
);
create table sam_itemFeedback_t (
   itemFeedbackId bigint generated by default as identity (start with 1),
   itemId bigint not null,
   typeId varchar(36) not null,
   text varchar(4000)
);
create table sam_itemMetaData_t (
   itemMetaDataId bigint generated by default as identity (start with 1),
   itemId bigint not null,
   label varchar(255) not null,
   entry varchar(255)
);
create table sam_assessAccessControl_t (
   assessmentId bigint not null,
   submissionsAllowed integer,
   unlimitedSubmissions integer,
   submissionsSaved integer,
   assessmentFormat integer,
   bookMarkingItem integer,
   timeLimit integer,
   timedAssessment integer,
   retryAllowed integer,
   lateHandling integer,
   startDate datetime,
   dueDate datetime,
   scoreDate datetime,
   feedbackDate datetime,
   retractDate datetime,
   autoSubmit integer,
   itemNavigation integer,
   itemNumbering integer,
   submissionMessage varchar(4000),
   releaseTo varchar(255),
   username varchar(255),
   password varchar(255),
   finalPageUrl varchar(1023),
   primary key (assessmentId)
);
create table sam_answer_t (
   answerId bigint generated by default as identity (start with 1),
   itemTextId bigint not null,
   itemId bigint not null,
   text varchar(4000),
   sequence integer not null,
   label varchar(20),
   isCorrect varchar(1),
   grade varchar(80),
   score float
);
create table sam_questionPoolAccess_t (
   questionPoolId bigint not null,
   agentId varchar(255) not null,
   accessTypeId bigint not null,
   primary key (questionPoolId, agentId, accessTypeId)
);
create table sam_assessMetaData_t (
   assessmentMetaDataId bigint generated by default as identity (start with 1),
   assessmentId bigint not null,
   label varchar(255) not null,
   entry varchar(255)
);
alter table sam_gradingSummary_t add constraint FK5F622E077BD8188B foreign key (publishedAssessmentId) references sam_publishedAssessment_t;
alter table sam_item_t add constraint FK80FB06A8D78B62E0 foreign key (sectionId) references sam_section_t;
alter table sam_publishedItem_t add constraint FK373D6576D78B62E0 foreign key (sectionId) references sam_publishedSection_t;
alter table sam_publishedItemMetaData_t add constraint FKBB428825B9BF0B8E foreign key (itemId) references sam_publishedItem_t;
alter table sam_publishedItemText_t add constraint FKD3215703B9BF0B8E foreign key (itemId) references sam_publishedItem_t;
alter table sam_securedIP_t add constraint FKAFEA10493660977D foreign key (assessmentId) references sam_assessmentBase_t;
alter table sam_section_t add constraint FKF358113A3660977D foreign key (assessmentId) references sam_assessmentBase_t;
alter table sam_publishedItemFeedback_t add constraint FKC8EB4EDBB9BF0B8E foreign key (itemId) references sam_publishedItem_t;
alter table sam_media_t add constraint FK585626792ED9513C foreign key (itemGradingId) references sam_itemGrading_t;
alter table sam_itemGrading_t add constraint FKF7272F9633FEB0A9 foreign key (publishedItemTextId) references sam_publishedItemText_t;
alter table sam_itemGrading_t add constraint FKF7272F964AF7EF1C foreign key (publishedItemId) references sam_publishedItem_t;
alter table sam_itemGrading_t add constraint FKF7272F96A9AE4A6D foreign key (assessmentGradingId) references sam_assessmentGrading_t;
alter table sam_itemGrading_t add constraint FKF7272F968C78987 foreign key (publishedAnswerId) references sam_publishedAnswer_t;
alter table sam_publishedEvaluation_t add constraint FKBEC6F0DF3660977D foreign key (assessmentId) references sam_publishedAssessment_t;
alter table sam_answerFeedback_t add constraint FKFB0830F8E2395179 foreign key (answerId) references sam_answer_t;
alter table sam_publishedFeedback_t add constraint FK81CC3A683660977D foreign key (assessmentId) references sam_publishedAssessment_t;
alter table sam_publishedSecuredIP_t add constraint FK59F8C23B3660977D foreign key (assessmentId) references sam_publishedAssessment_t;
alter table sam_publishedAssessment_t add constraint FKDCE056E53660977D foreign key (assessmentId) references sam_assessmentBase_t;
alter table sam_itemText_t add constraint FKD5E70F35B9BF0B8E foreign key (itemId) references sam_item_t;
alter table sam_assessFeedback_t add constraint FKF7B68D1E3660977D foreign key (assessmentId) references sam_assessmentBase_t;
alter table sam_publishedAccessControl_t add constraint FK552FA5A03660977D foreign key (assessmentId) references sam_publishedAssessment_t;
alter table sam_publishedAnswerFeedback_t add constraint FK1074E646E2395179 foreign key (answerId) references sam_publishedAnswer_t;
alter table sam_assessEvaluation_t add constraint FK63676E153660977D foreign key (assessmentId) references sam_assessmentBase_t;
alter table sam_publishedAnswer_t add constraint FKF97E97E1781E441B foreign key (itemTextId) references sam_publishedItemText_t;
alter table sam_publishedAnswer_t add constraint FKF97E97E1B9BF0B8E foreign key (itemId) references sam_publishedItem_t;
create index sam_authz_functionId_idx on sam_authzData_t (functionId);
create index sam_authz_qualifierId_idx on sam_authzData_t (qualifierId);
create index sam_authz_agentId_idx on sam_authzData_t (agentId);
alter table sam_assessmentGrading_t add constraint FK48D0F0C77BD8188B foreign key (publishedAssessmentId) references sam_publishedAssessment_t;
alter table sam_publishedSection_t add constraint FKA8EE97AC3660977D foreign key (assessmentId) references sam_publishedAssessment_t;
alter table sam_publishedMetaData_t add constraint FK742373B23660977D foreign key (assessmentId) references sam_publishedAssessment_t;
alter table sam_itemFeedback_t add constraint FK4D59E0DB9BF0B8E foreign key (itemId) references sam_item_t;
alter table sam_itemMetaData_t add constraint FKF72CD757B9BF0B8E foreign key (itemId) references sam_item_t;
alter table sam_assessAccessControl_t add constraint FK257A94AA3660977D foreign key (assessmentId) references sam_assessmentBase_t;
alter table sam_answer_t add constraint FKCA58B493B9BF0B8E foreign key (itemId) references sam_item_t;
alter table sam_answer_t add constraint FKCA58B493781E441B foreign key (itemTextId) references sam_itemText_t;
alter table sam_assessMetaData_t add constraint FKEA0DC6683660977D foreign key (assessmentId) references sam_assessmentBase_t;
commit;