@sakai_alias.sql
@chef_announcement.sql
@chef_assignment.sql
@chef_calendar.sql
@chef_chat.sql
@sakai_cluster.sql
@chef_content.sql
@chef_digest.sql
@chef_discussion.sql
@chef_event.sql
@chef_id.sql
@chef_mailarchive.sql
@chef_notification.sql
@chef_preferences.sql
@chef_presence.sql
@sakai_realm.sql
@sakai_realm_populate.sql
@chef_session.sql
@sakai_site.sql
@sakai_site_populate.sql
@sakai_locks.sql
@sakai_user.sql
@sakai_resources.sql
@sakai_admin.sql
