-----------------------------------------------------------------------------
-- CHEF_SESSION
-----------------------------------------------------------------------------

DROP TABLE CHEF_SESSION;

CREATE TABLE CHEF_SESSION
(
	SESSION_ID VARCHAR2 (32),
	SESSION_SERVER VARCHAR2 (64),
	SESSION_USER VARCHAR2 (99),
	SESSION_IP VARCHAR2 (16),
	SESSION_USER_AGENT VARCHAR2 (256),
	SESSION_START DATE,
	SESSION_END DATE
);

CREATE UNIQUE INDEX CHEF_SESSION_INDEX ON CHEF_SESSION
(
	SESSION_ID
);

CREATE INDEX CHEF_SESSION_SERVER_INDEX ON CHEF_SESSION
(
	SESSION_SERVER
);
