-----------------------------------------------------------------------------
-- DISSERTATION_DISSERTATION
-----------------------------------------------------------------------------

DROP TABLE DISSERTATION_DISSERTATION;

CREATE TABLE DISSERTATION_DISSERTATION
(
    DISSERTATION_ID VARCHAR2 (99) NOT NULL,
    XML LONG,
    SITE VARCHAR2(100),
    TYPE VARCHAR2(100)
);

CREATE UNIQUE INDEX DISSERTATION_DISS_INDEX ON DISSERTATION_DISSERTATION
(
	DISSERTATION_ID
);

CREATE INDEX IE_DISS_DISS_SITE ON DISSERTATION_DISSERTATION
(
	SITE	ASC
);

CREATE INDEX IE_DISS_DISS_TYPE ON DISSERTATION_DISSERTATION
(
	TYPE ASC
);

CREATE INDEX IE_DISS_DISS_SITE_TYPE ON DISSERTATION_DISSERTATION
(
	SITE	ASC,
	TYPE	ASC
);

-----------------------------------------------------------------------------
-- DISSERTATION_GROUP
-----------------------------------------------------------------------------

DROP TABLE DISSERTATION_GROUP;

CREATE TABLE DISSERTATION_GROUP
(
    GROUP_ID VARCHAR2 (99) NOT NULL,
    XML LONG
);

CREATE UNIQUE INDEX DISSERTATION_GROUP_INDEX ON DISSERTATION_GROUP
(
	GROUP_ID
);

-----------------------------------------------------------------------------
-- DISSERTATION_STEP
-----------------------------------------------------------------------------

DROP TABLE DISSERTATION_STEP;

CREATE TABLE DISSERTATION_STEP
(
    STEP_ID VARCHAR2 (99) NOT NULL,
    XML LONG
);

CREATE UNIQUE INDEX DISSERTATION_STEP_INDEX ON DISSERTATION_STEP
(
	STEP_ID
);

-----------------------------------------------------------------------------
-- DISSERTATION_PATH
-----------------------------------------------------------------------------

DROP TABLE DISSERTATION_PATH;

CREATE TABLE DISSERTATION_PATH
(
    PATH_ID VARCHAR2 (99) NOT NULL,
    XML LONG,
    CANDIDATE VARCHAR2(100),
    PARENTSITE VARCHAR2(100),
    SORTLETTER CHAR,
    TYPE VARCHAR2(100),
    SITE VARCHAR2(100)
);

CREATE UNIQUE INDEX DISSERTATION_PATH_INDEX ON DISSERTATION_PATH
(
	PATH_ID
);

CREATE INDEX IE_DISS_PATH_CANDIDATE ON DISSERTATION_PATH
(
	CANDIDATE	ASC
);

CREATE INDEX IE_DISS_PATH_PARENTSITE ON DISSERTATION_PATH
(
	PARENTSITE	ASC
);

CREATE INDEX IE_DISS_PATH_SITE ON DISSERTATION_PATH
(
	SITE	ASC
);

CREATE INDEX IE_DISS_PATH_SORTLETTER_TYPE ON DISSERTATION_PATH
(
	SORTLETTER	ASC,
	TYPE		ASC
);

CREATE INDEX IE_DISS_PATH_TYPE ON DISSERTATION_PATH
(
	TYPE	ASC
);

-----------------------------------------------------------------------------
-- DISSERTATION_STATUS
-----------------------------------------------------------------------------

DROP TABLE DISSERTATION_STATUS;

CREATE TABLE DISSERTATION_STATUS
(
    STATUS_ID VARCHAR2 (99) NOT NULL,
    XML LONG
);

CREATE UNIQUE INDEX DISSERTATION_STATUS_INDEX ON DISSERTATION_STATUS
(
	STATUS_ID
);

-----------------------------------------------------------------------------
-- DISSERTATION_CANDIDATEINFO
-----------------------------------------------------------------------------

DROP TABLE DISSERTATION_CANDIDATEINFO;

CREATE TABLE DISSERTATION_CANDIDATEINFO
(
    INFO_ID VARCHAR2 (99) NOT NULL,
    XML LONG,
    CHEFID VARCHAR2(100),
    PARENTSITE VARCHAR2(100),
    EMPLID VARCHAR2(8)
);

CREATE UNIQUE INDEX DISSERTATION_INFO_INDEX ON DISSERTATION_CANDIDATEINFO
(
	INFO_ID
);

CREATE INDEX IE_DISS_INFO_CHEFID ON DISSERTATION_CANDIDATEINFO
(
	CHEFID	ASC
);

CREATE INDEX IE_DISS_INFO_CHEFID_PARENTSITE ON DISSERTATION_CANDIDATEINFO
(
	CHEFID	ASC,
	PARENTSITE	ASC
);

CREATE INDEX IE_DISS_INFO_EMPLID ON DISSERTATION_CANDIDATEINFO
(
	EMPLID	ASC
);

