-----------------------------------------------------------------------------
-- CHEF_SESSION
-----------------------------------------------------------------------------

DROP TABLE IF EXISTS CHEF_SESSION;

CREATE TABLE CHEF_SESSION
(
	SESSION_ID VARCHAR (32),
	SESSION_SERVER VARCHAR (64),
	SESSION_USER VARCHAR (99),
	SESSION_IP VARCHAR (16),
	SESSION_USER_AGENT VARCHAR (255),
	SESSION_START DATETIME,
	SESSION_END DATETIME
);

CREATE UNIQUE INDEX CHEF_SESSION_INDEX ON CHEF_SESSION
(
	SESSION_ID
);

CREATE INDEX CHEF_SESSION_SERVER_INDEX ON CHEF_SESSION
(
	SESSION_SERVER
);

DESCRIBE CHEF_SESSION;

