-- the active locks
SET PAGESIZE 5000;
COLUMN TABLE_NAME FORMAT A20
COLUMN RECORD_ID FORMAT A20
COLUMN SESSION_USER FORMAT A32
COLUMN SESSION_SERVER FORMAT A32

select
	TABLE_NAME, RECORD_ID, to_char(LOCK_TIME,'YYYY-MM-DD HH24:MI:SS'), USAGE_SESSION_ID, SESSION_USER, SESSION_SERVER
from SAKAI_LOCKS, CHEF_SESSION
where USAGE_SESSION_ID = SESSION_ID
order by LOCK_TIME ASC
;

--Locks from closed sessions
select SL.TABLE_NAME, SL.RECORD_ID, 
  to_char(SL.LOCK_TIME,'YYYY-MM-DD HH24:MI:SS') as LOCK_TIME, 
  SL.USAGE_SESSION_ID,
  CS.SESSION_USER, 
  CS.SESSION_SERVER, 
  to_char(CS.SESSION_END, 'YYYY-MM-DD HH24:MI:DD') as SESSION_END
from SAKAI_LOCKS SL, CHEF_SESSION CS
where SL.USAGE_SESSION_ID = CS.SESSION_ID
and SL.USAGE_SESSION_ID NOT IN 
  (select session_id from chef_session where SESSION_START = SESSION_END)
order by SL.LOCK_TIME ASC;

-- clear locks from closed sessions
--delete from sakai_locks where usage_session_id NOT IN (select SL.USAGE_SESSION_ID from SAKAI_LOCKS SL, CHEF_SESSION CS where SL.USAGE_SESSION_ID = CS.SESSION_ID and CS.SESSION_START = CS.SESSION_END);
